// generated by stringer -type Converter; DO NOT EDIT

package hydra

import "fmt"

const _Converter_name = "ConvertBoolConvertIntConvertFloat"

var _Converter_index = [...]uint8{11, 21, 33}

func (i Converter) String() string {
	i -= 1
	if i < 0 || i >= Converter(len(_Converter_index)) {
		return fmt.Sprintf("Converter(%d)", i+1)
	}
	hi := _Converter_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Converter_index[i-1]
	}
	return _Converter_name[lo:hi]
}
