// generated by stringer -type FileFormat; DO NOT EDIT

package hydra

import "fmt"

const _FileFormat_name = "FormatNoneFormatLTSVFormatJSONFormatRegexp"

var _FileFormat_index = [...]uint8{0, 10, 20, 30, 42}

func (i FileFormat) String() string {
	if i < 0 || i >= FileFormat(len(_FileFormat_index)-1) {
		return fmt.Sprintf("FileFormat(%d)", i)
	}
	return _FileFormat_name[_FileFormat_index[i]:_FileFormat_index[i+1]]
}
